### PR TITLE
Changed the "title categorys", added gdrive download instuctions

### PR DESCRIPTION
**Pull request by MollerVictor**
Changed the "title categorys" so it better fit with the content inside it.

Tried to make it a bit easier to understand what things are optional and what things are a path split.

Also removed the top line where it asks you to git clone, since if you have that file open you should have already done the git clone part.

Added instructions how to download it to your google drive.

Feel free test, and add/remove things as needed.

### CODE REVIEW

**Comment by djbielejeski** [comment]
@MollerVictor can you re-merge with main?

**Comment by MollerVictor** [comment]
@djbielejeski It should be fine now

**Comment by djbielejeski** [comment]
Not sure if these will work on colab (the extra newlines)
image

And you have a merge conflict (probably because of my recent changes)
image

**Comment by MollerVictor** [comment]
oh it changed the line endings yeah that's bad. But the only good thing about this merge is the google drive stuff at the bottom. So I would say close this merge request and add the google drive bit yourself.

**Pull request closed without merging**
