### PR TITLE
More logs

### PR DESCRIPTION
**Pull request by GpuLover**
create a json file when training a model with all the parameters used

add a flag to stable_txt2img to create a json file describing the prompt and all parameter used.

### CODE REVIEW

**Comment by GpuLover** [comment]
tested locally and working fine

**Comment by JoePenna** [comment]
@GpuLover would love to merge this in! could you resolve that conflict?

**Comment by GpuLover** [comment]
now using opt.__dict__ so it automaticallty updates if argument are added to the parsers in the future

both commit are tested and working

**Comment by GpuLover** [comment]
@JoePenna Done

**Comment by djbielejeski** [comment]
Added in the Simple colab script

**Pull request closed without merging**
