### PR TITLE
Param passing

### PR DESCRIPTION
**Pull request by fabbarix**
Allows passing the subject from the command line.

  Also adds a `--subject_only` switch to train using only the placeholder string.

### CODE REVIEW

**Comment by fabbarix** [comment]
Did the conflict resolution directly in Github - this will need some testing to make sure I didn't break things.

**Comment by djbielejeski** [comment]
@fabbarix could you remake off of `main` again now that our `--token` param has been added?  I think the only thing we'll need is the flag for --subject_only, and I think that should be in both jupyter colabs by default

**Comment by fabbarix** [comment]
Will do!

**Comment by fabbarix** [comment]
Created a simpler version of this, rebased on main.

**Pull request closed without merging**
